# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/actionlib_msgs/GoalStatusArray.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.actionlib_msgs import GoalStatus_pb2 as ros_dot_actionlib__msgs_dot_GoalStatus__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(ros/actionlib_msgs/GoalStatusArray.proto\x12\x12ros.actionlib_msgs\x1a#ros/actionlib_msgs/GoalStatus.proto\x1a\x19ros/std_msgs/Header.proto\"l\n\x0fGoalStatusArray\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x33\n\x0bstatus_list\x18\x02 \x03(\x0b\x32\x1e.ros.actionlib_msgs.GoalStatusb\x06proto3')



_GOALSTATUSARRAY = DESCRIPTOR.message_types_by_name['GoalStatusArray']
GoalStatusArray = _reflection.GeneratedProtocolMessageType('GoalStatusArray', (_message.Message,), {
  'DESCRIPTOR' : _GOALSTATUSARRAY,
  '__module__' : 'ros.actionlib_msgs.GoalStatusArray_pb2'
  # @@protoc_insertion_point(class_scope:ros.actionlib_msgs.GoalStatusArray)
  })
_sym_db.RegisterMessage(GoalStatusArray)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GOALSTATUSARRAY._serialized_start=128
  _GOALSTATUSARRAY._serialized_end=236
# @@protoc_insertion_point(module_scope)
