# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/ByteMultiArray.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.std_msgs import MultiArrayLayout_pb2 as ros_dot_std__msgs_dot_MultiArrayLayout__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ros/std_msgs/ByteMultiArray.proto\x12\x0cros.std_msgs\x1a#ros/std_msgs/MultiArrayLayout.proto\"N\n\x0e\x42yteMultiArray\x12.\n\x06layout\x18\x01 \x01(\x0b\x32\x1e.ros.std_msgs.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x11\x62\x06proto3')



_BYTEMULTIARRAY = DESCRIPTOR.message_types_by_name['ByteMultiArray']
ByteMultiArray = _reflection.GeneratedProtocolMessageType('ByteMultiArray', (_message.Message,), {
  'DESCRIPTOR' : _BYTEMULTIARRAY,
  '__module__' : 'ros.std_msgs.ByteMultiArray_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.ByteMultiArray)
  })
_sym_db.RegisterMessage(ByteMultiArray)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BYTEMULTIARRAY._serialized_start=88
  _BYTEMULTIARRAY._serialized_end=166
# @@protoc_insertion_point(module_scope)
