# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/ColorRGBA.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cros/std_msgs/ColorRGBA.proto\x12\x0cros.std_msgs\"7\n\tColorRGBA\x12\t\n\x01r\x18\x01 \x01(\x02\x12\t\n\x01g\x18\x02 \x01(\x02\x12\t\n\x01\x62\x18\x03 \x01(\x02\x12\t\n\x01\x61\x18\x04 \x01(\x02\x62\x06proto3')



_COLORRGBA = DESCRIPTOR.message_types_by_name['ColorRGBA']
ColorRGBA = _reflection.GeneratedProtocolMessageType('ColorRGBA', (_message.Message,), {
  'DESCRIPTOR' : _COLORRGBA,
  '__module__' : 'ros.std_msgs.ColorRGBA_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.ColorRGBA)
  })
_sym_db.RegisterMessage(ColorRGBA)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COLORRGBA._serialized_start=46
  _COLORRGBA._serialized_end=101
# @@protoc_insertion_point(module_scope)
