# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/Duration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros import builtins_pb2 as ros_dot_builtins__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bros/std_msgs/Duration.proto\x12\x0cros.std_msgs\x1a\x12ros/builtins.proto\"\'\n\x08\x44uration\x12\x1b\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\r.ros.Durationb\x06proto3')



_DURATION = DESCRIPTOR.message_types_by_name['Duration']
Duration = _reflection.GeneratedProtocolMessageType('Duration', (_message.Message,), {
  'DESCRIPTOR' : _DURATION,
  '__module__' : 'ros.std_msgs.Duration_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.Duration)
  })
_sym_db.RegisterMessage(Duration)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DURATION._serialized_start=65
  _DURATION._serialized_end=104
# @@protoc_insertion_point(module_scope)
