# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/Float64MultiArray.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.std_msgs import MultiArrayLayout_pb2 as ros_dot_std__msgs_dot_MultiArrayLayout__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ros/std_msgs/Float64MultiArray.proto\x12\x0cros.std_msgs\x1a#ros/std_msgs/MultiArrayLayout.proto\"Q\n\x11\x46loat64MultiArray\x12.\n\x06layout\x18\x01 \x01(\x0b\x32\x1e.ros.std_msgs.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x01\x62\x06proto3')



_FLOAT64MULTIARRAY = DESCRIPTOR.message_types_by_name['Float64MultiArray']
Float64MultiArray = _reflection.GeneratedProtocolMessageType('Float64MultiArray', (_message.Message,), {
  'DESCRIPTOR' : _FLOAT64MULTIARRAY,
  '__module__' : 'ros.std_msgs.Float64MultiArray_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.Float64MultiArray)
  })
_sym_db.RegisterMessage(Float64MultiArray)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLOAT64MULTIARRAY._serialized_start=91
  _FLOAT64MULTIARRAY._serialized_end=172
# @@protoc_insertion_point(module_scope)
