# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/Int8.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ros/std_msgs/Int8.proto\x12\x0cros.std_msgs\"\x14\n\x04Int8\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x11\x62\x06proto3')



_INT8 = DESCRIPTOR.message_types_by_name['Int8']
Int8 = _reflection.GeneratedProtocolMessageType('Int8', (_message.Message,), {
  'DESCRIPTOR' : _INT8,
  '__module__' : 'ros.std_msgs.Int8_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.Int8)
  })
_sym_db.RegisterMessage(Int8)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INT8._serialized_start=41
  _INT8._serialized_end=61
# @@protoc_insertion_point(module_scope)
