# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/MultiArrayDimension.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ros/std_msgs/MultiArrayDimension.proto\x12\x0cros.std_msgs\"B\n\x13MultiArrayDimension\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\r\x12\x0e\n\x06stride\x18\x03 \x01(\rb\x06proto3')



_MULTIARRAYDIMENSION = DESCRIPTOR.message_types_by_name['MultiArrayDimension']
MultiArrayDimension = _reflection.GeneratedProtocolMessageType('MultiArrayDimension', (_message.Message,), {
  'DESCRIPTOR' : _MULTIARRAYDIMENSION,
  '__module__' : 'ros.std_msgs.MultiArrayDimension_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.MultiArrayDimension)
  })
_sym_db.RegisterMessage(MultiArrayDimension)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MULTIARRAYDIMENSION._serialized_start=56
  _MULTIARRAYDIMENSION._serialized_end=122
# @@protoc_insertion_point(module_scope)
