# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/visualization_msgs/InteractiveMarker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Pose_pb2 as ros_dot_geometry__msgs_dot_Pose__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2
from ros.visualization_msgs import InteractiveMarkerControl_pb2 as ros_dot_visualization__msgs_dot_InteractiveMarkerControl__pb2
from ros.visualization_msgs import MenuEntry_pb2 as ros_dot_visualization__msgs_dot_MenuEntry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.ros/visualization_msgs/InteractiveMarker.proto\x12\x16ros.visualization_msgs\x1a\x1cros/geometry_msgs/Pose.proto\x1a\x19ros/std_msgs/Header.proto\x1a\x35ros/visualization_msgs/InteractiveMarkerControl.proto\x1a&ros/visualization_msgs/MenuEntry.proto\"\x8f\x02\n\x11InteractiveMarker\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12%\n\x04pose\x18\x02 \x01(\x0b\x32\x17.ros.geometry_msgs.Pose\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05scale\x18\x05 \x01(\x02\x12\x37\n\x0cmenu_entries\x18\x06 \x03(\x0b\x32!.ros.visualization_msgs.MenuEntry\x12\x42\n\x08\x63ontrols\x18\x07 \x03(\x0b\x32\x30.ros.visualization_msgs.InteractiveMarkerControlb\x06proto3')



_INTERACTIVEMARKER = DESCRIPTOR.message_types_by_name['InteractiveMarker']
InteractiveMarker = _reflection.GeneratedProtocolMessageType('InteractiveMarker', (_message.Message,), {
  'DESCRIPTOR' : _INTERACTIVEMARKER,
  '__module__' : 'ros.visualization_msgs.InteractiveMarker_pb2'
  # @@protoc_insertion_point(class_scope:ros.visualization_msgs.InteractiveMarker)
  })
_sym_db.RegisterMessage(InteractiveMarker)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTERACTIVEMARKER._serialized_start=227
  _INTERACTIVEMARKER._serialized_end=498
# @@protoc_insertion_point(module_scope)
