# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/visualization_msgs/InteractiveMarkerControl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Quaternion_pb2 as ros_dot_geometry__msgs_dot_Quaternion__pb2
from ros.visualization_msgs import Marker_pb2 as ros_dot_visualization__msgs_dot_Marker__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5ros/visualization_msgs/InteractiveMarkerControl.proto\x12\x16ros.visualization_msgs\x1a\"ros/geometry_msgs/Quaternion.proto\x1a#ros/visualization_msgs/Marker.proto\"\x96\x02\n\x18InteractiveMarkerControl\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x32\n\x0borientation\x18\x02 \x01(\x0b\x32\x1d.ros.geometry_msgs.Quaternion\x12\x18\n\x10orientation_mode\x18\x03 \x01(\x05\x12\x18\n\x10interaction_mode\x18\x04 \x01(\x05\x12\x16\n\x0e\x61lways_visible\x18\x05 \x01(\x08\x12/\n\x07markers\x18\x06 \x03(\x0b\x32\x1e.ros.visualization_msgs.Marker\x12&\n\x1eindependent_marker_orientation\x18\x07 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\tb\x06proto3')



_INTERACTIVEMARKERCONTROL = DESCRIPTOR.message_types_by_name['InteractiveMarkerControl']
InteractiveMarkerControl = _reflection.GeneratedProtocolMessageType('InteractiveMarkerControl', (_message.Message,), {
  'DESCRIPTOR' : _INTERACTIVEMARKERCONTROL,
  '__module__' : 'ros.visualization_msgs.InteractiveMarkerControl_pb2'
  # @@protoc_insertion_point(class_scope:ros.visualization_msgs.InteractiveMarkerControl)
  })
_sym_db.RegisterMessage(InteractiveMarkerControl)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTERACTIVEMARKERCONTROL._serialized_start=155
  _INTERACTIVEMARKERCONTROL._serialized_end=433
# @@protoc_insertion_point(module_scope)
