# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/visualization_msgs/Marker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros import builtins_pb2 as ros_dot_builtins__pb2
from ros.geometry_msgs import Point_pb2 as ros_dot_geometry__msgs_dot_Point__pb2
from ros.geometry_msgs import Pose_pb2 as ros_dot_geometry__msgs_dot_Pose__pb2
from ros.geometry_msgs import Vector3_pb2 as ros_dot_geometry__msgs_dot_Vector3__pb2
from ros.std_msgs import ColorRGBA_pb2 as ros_dot_std__msgs_dot_ColorRGBA__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ros/visualization_msgs/Marker.proto\x12\x16ros.visualization_msgs\x1a\x12ros/builtins.proto\x1a\x1dros/geometry_msgs/Point.proto\x1a\x1cros/geometry_msgs/Pose.proto\x1a\x1fros/geometry_msgs/Vector3.proto\x1a\x1cros/std_msgs/ColorRGBA.proto\x1a\x19ros/std_msgs/Header.proto\"\xb2\x03\n\x06Marker\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\n\n\x02ns\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\x05\x12%\n\x04pose\x18\x06 \x01(\x0b\x32\x17.ros.geometry_msgs.Pose\x12)\n\x05scale\x18\x07 \x01(\x0b\x32\x1a.ros.geometry_msgs.Vector3\x12&\n\x05\x63olor\x18\x08 \x01(\x0b\x32\x17.ros.std_msgs.ColorRGBA\x12\x1f\n\x08lifetime\x18\t \x01(\x0b\x32\r.ros.Duration\x12\x14\n\x0c\x66rame_locked\x18\n \x01(\x08\x12(\n\x06points\x18\x0b \x03(\x0b\x32\x18.ros.geometry_msgs.Point\x12\'\n\x06\x63olors\x18\x0c \x03(\x0b\x32\x17.ros.std_msgs.ColorRGBA\x12\x0c\n\x04text\x18\r \x01(\t\x12\x15\n\rmesh_resource\x18\x0e \x01(\t\x12#\n\x1bmesh_use_embedded_materials\x18\x0f \x01(\x08\x62\x06proto3')



_MARKER = DESCRIPTOR.message_types_by_name['Marker']
Marker = _reflection.GeneratedProtocolMessageType('Marker', (_message.Message,), {
  'DESCRIPTOR' : _MARKER,
  '__module__' : 'ros.visualization_msgs.Marker_pb2'
  # @@protoc_insertion_point(class_scope:ros.visualization_msgs.Marker)
  })
_sym_db.RegisterMessage(Marker)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MARKER._serialized_start=235
  _MARKER._serialized_end=669
# @@protoc_insertion_point(module_scope)
