# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/visualization_msgs/MenuEntry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ros/visualization_msgs/MenuEntry.proto\x12\x16ros.visualization_msgs\"`\n\tMenuEntry\x12\n\n\x02id\x18\x01 \x01(\r\x12\x11\n\tparent_id\x18\x02 \x01(\r\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x04 \x01(\t\x12\x14\n\x0c\x63ommand_type\x18\x05 \x01(\x05\x62\x06proto3')



_MENUENTRY = DESCRIPTOR.message_types_by_name['MenuEntry']
MenuEntry = _reflection.GeneratedProtocolMessageType('MenuEntry', (_message.Message,), {
  'DESCRIPTOR' : _MENUENTRY,
  '__module__' : 'ros.visualization_msgs.MenuEntry_pb2'
  # @@protoc_insertion_point(class_scope:ros.visualization_msgs.MenuEntry)
  })
_sym_db.RegisterMessage(MenuEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MENUENTRY._serialized_start=66
  _MENUENTRY._serialized_end=162
# @@protoc_insertion_point(module_scope)
