# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/shape_msgs/MeshTriangle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ros/shape_msgs/MeshTriangle.proto\x12\x0eros.shape_msgs\"&\n\x0cMeshTriangle\x12\x16\n\x0evertex_indices\x18\x01 \x03(\rb\x06proto3')



_MESHTRIANGLE = DESCRIPTOR.message_types_by_name['MeshTriangle']
MeshTriangle = _reflection.GeneratedProtocolMessageType('MeshTriangle', (_message.Message,), {
  'DESCRIPTOR' : _MESHTRIANGLE,
  '__module__' : 'ros.shape_msgs.MeshTriangle_pb2'
  # @@protoc_insertion_point(class_scope:ros.shape_msgs.MeshTriangle)
  })
_sym_db.RegisterMessage(MeshTriangle)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESHTRIANGLE._serialized_start=53
  _MESHTRIANGLE._serialized_end=91
# @@protoc_insertion_point(module_scope)
