# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/shape_msgs/Plane.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aros/shape_msgs/Plane.proto\x12\x0eros.shape_msgs\"\x15\n\x05Plane\x12\x0c\n\x04\x63oef\x18\x01 \x03(\x01\x62\x06proto3')



_PLANE = DESCRIPTOR.message_types_by_name['Plane']
Plane = _reflection.GeneratedProtocolMessageType('Plane', (_message.Message,), {
  'DESCRIPTOR' : _PLANE,
  '__module__' : 'ros.shape_msgs.Plane_pb2'
  # @@protoc_insertion_point(class_scope:ros.shape_msgs.Plane)
  })
_sym_db.RegisterMessage(Plane)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLANE._serialized_start=46
  _PLANE._serialized_end=67
# @@protoc_insertion_point(module_scope)
