# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/AccelWithCovarianceStamped.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import AccelWithCovariance_pb2 as ros_dot_geometry__msgs_dot_AccelWithCovariance__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2ros/geometry_msgs/AccelWithCovarianceStamped.proto\x12\x11ros.geometry_msgs\x1a+ros/geometry_msgs/AccelWithCovariance.proto\x1a\x19ros/std_msgs/Header.proto\"y\n\x1a\x41\x63\x63\x65lWithCovarianceStamped\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x35\n\x05\x61\x63\x63\x65l\x18\x02 \x01(\x0b\x32&.ros.geometry_msgs.AccelWithCovarianceb\x06proto3')



_ACCELWITHCOVARIANCESTAMPED = DESCRIPTOR.message_types_by_name['AccelWithCovarianceStamped']
AccelWithCovarianceStamped = _reflection.GeneratedProtocolMessageType('AccelWithCovarianceStamped', (_message.Message,), {
  'DESCRIPTOR' : _ACCELWITHCOVARIANCESTAMPED,
  '__module__' : 'ros.geometry_msgs.AccelWithCovarianceStamped_pb2'
  # @@protoc_insertion_point(class_scope:ros.geometry_msgs.AccelWithCovarianceStamped)
  })
_sym_db.RegisterMessage(AccelWithCovarianceStamped)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCELWITHCOVARIANCESTAMPED._serialized_start=145
  _ACCELWITHCOVARIANCESTAMPED._serialized_end=266
# @@protoc_insertion_point(module_scope)
