# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/InertiaStamped.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Inertia_pb2 as ros_dot_geometry__msgs_dot_Inertia__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ros/geometry_msgs/InertiaStamped.proto\x12\x11ros.geometry_msgs\x1a\x1fros/geometry_msgs/Inertia.proto\x1a\x19ros/std_msgs/Header.proto\"c\n\x0eInertiaStamped\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12+\n\x07inertia\x18\x02 \x01(\x0b\x32\x1a.ros.geometry_msgs.Inertiab\x06proto3')



_INERTIASTAMPED = DESCRIPTOR.message_types_by_name['InertiaStamped']
InertiaStamped = _reflection.GeneratedProtocolMessageType('InertiaStamped', (_message.Message,), {
  'DESCRIPTOR' : _INERTIASTAMPED,
  '__module__' : 'ros.geometry_msgs.InertiaStamped_pb2'
  # @@protoc_insertion_point(class_scope:ros.geometry_msgs.InertiaStamped)
  })
_sym_db.RegisterMessage(InertiaStamped)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INERTIASTAMPED._serialized_start=121
  _INERTIASTAMPED._serialized_end=220
# @@protoc_insertion_point(module_scope)
