# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/PoseWithCovariance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Pose_pb2 as ros_dot_geometry__msgs_dot_Pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*ros/geometry_msgs/PoseWithCovariance.proto\x12\x11ros.geometry_msgs\x1a\x1cros/geometry_msgs/Pose.proto\"O\n\x12PoseWithCovariance\x12%\n\x04pose\x18\x01 \x01(\x0b\x32\x17.ros.geometry_msgs.Pose\x12\x12\n\ncovariance\x18\x02 \x03(\x01\x62\x06proto3')



_POSEWITHCOVARIANCE = DESCRIPTOR.message_types_by_name['PoseWithCovariance']
PoseWithCovariance = _reflection.GeneratedProtocolMessageType('PoseWithCovariance', (_message.Message,), {
  'DESCRIPTOR' : _POSEWITHCOVARIANCE,
  '__module__' : 'ros.geometry_msgs.PoseWithCovariance_pb2'
  # @@protoc_insertion_point(class_scope:ros.geometry_msgs.PoseWithCovariance)
  })
_sym_db.RegisterMessage(PoseWithCovariance)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSEWITHCOVARIANCE._serialized_start=95
  _POSEWITHCOVARIANCE._serialized_end=174
# @@protoc_insertion_point(module_scope)
