# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/Vector3Stamped.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Vector3_pb2 as ros_dot_geometry__msgs_dot_Vector3__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ros/geometry_msgs/Vector3Stamped.proto\x12\x11ros.geometry_msgs\x1a\x1fros/geometry_msgs/Vector3.proto\x1a\x19ros/std_msgs/Header.proto\"b\n\x0eVector3Stamped\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12*\n\x06vector\x18\x02 \x01(\x0b\x32\x1a.ros.geometry_msgs.Vector3b\x06proto3')



_VECTOR3STAMPED = DESCRIPTOR.message_types_by_name['Vector3Stamped']
Vector3Stamped = _reflection.GeneratedProtocolMessageType('Vector3Stamped', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3STAMPED,
  '__module__' : 'ros.geometry_msgs.Vector3Stamped_pb2'
  # @@protoc_insertion_point(class_scope:ros.geometry_msgs.Vector3Stamped)
  })
_sym_db.RegisterMessage(Vector3Stamped)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTOR3STAMPED._serialized_start=121
  _VECTOR3STAMPED._serialized_end=219
# @@protoc_insertion_point(module_scope)
