# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/Bool.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ros/std_msgs/Bool.proto\x12\x0cros.std_msgs\"\x14\n\x04\x42ool\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x08\x62\x06proto3')



_BOOL = DESCRIPTOR.message_types_by_name['Bool']
Bool = _reflection.GeneratedProtocolMessageType('Bool', (_message.Message,), {
  'DESCRIPTOR' : _BOOL,
  '__module__' : 'ros.std_msgs.Bool_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.Bool)
  })
_sym_db.RegisterMessage(Bool)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOL._serialized_start=41
  _BOOL._serialized_end=61
# @@protoc_insertion_point(module_scope)
