# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/Char.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ros/std_msgs/Char.proto\x12\x0cros.std_msgs\"\x14\n\x04\x43har\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05\x62\x06proto3')



_CHAR = DESCRIPTOR.message_types_by_name['Char']
Char = _reflection.GeneratedProtocolMessageType('Char', (_message.Message,), {
  'DESCRIPTOR' : _CHAR,
  '__module__' : 'ros.std_msgs.Char_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.Char)
  })
_sym_db.RegisterMessage(Char)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHAR._serialized_start=41
  _CHAR._serialized_end=61
# @@protoc_insertion_point(module_scope)
