# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/Float32.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aros/std_msgs/Float32.proto\x12\x0cros.std_msgs\"\x17\n\x07\x46loat32\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x02\x62\x06proto3')



_FLOAT32 = DESCRIPTOR.message_types_by_name['Float32']
Float32 = _reflection.GeneratedProtocolMessageType('Float32', (_message.Message,), {
  'DESCRIPTOR' : _FLOAT32,
  '__module__' : 'ros.std_msgs.Float32_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.Float32)
  })
_sym_db.RegisterMessage(Float32)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLOAT32._serialized_start=44
  _FLOAT32._serialized_end=67
# @@protoc_insertion_point(module_scope)
