# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/Int32.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18ros/std_msgs/Int32.proto\x12\x0cros.std_msgs\"\x15\n\x05Int32\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05\x62\x06proto3')



_INT32 = DESCRIPTOR.message_types_by_name['Int32']
Int32 = _reflection.GeneratedProtocolMessageType('Int32', (_message.Message,), {
  'DESCRIPTOR' : _INT32,
  '__module__' : 'ros.std_msgs.Int32_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.Int32)
  })
_sym_db.RegisterMessage(Int32)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INT32._serialized_start=42
  _INT32._serialized_end=63
# @@protoc_insertion_point(module_scope)
