# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/MultiArrayLayout.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.std_msgs import MultiArrayDimension_pb2 as ros_dot_std__msgs_dot_MultiArrayDimension__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ros/std_msgs/MultiArrayLayout.proto\x12\x0cros.std_msgs\x1a&ros/std_msgs/MultiArrayDimension.proto\"W\n\x10MultiArrayLayout\x12.\n\x03\x64im\x18\x01 \x03(\x0b\x32!.ros.std_msgs.MultiArrayDimension\x12\x13\n\x0b\x64\x61ta_offset\x18\x02 \x01(\rb\x06proto3')



_MULTIARRAYLAYOUT = DESCRIPTOR.message_types_by_name['MultiArrayLayout']
MultiArrayLayout = _reflection.GeneratedProtocolMessageType('MultiArrayLayout', (_message.Message,), {
  'DESCRIPTOR' : _MULTIARRAYLAYOUT,
  '__module__' : 'ros.std_msgs.MultiArrayLayout_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.MultiArrayLayout)
  })
_sym_db.RegisterMessage(MultiArrayLayout)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MULTIARRAYLAYOUT._serialized_start=93
  _MULTIARRAYLAYOUT._serialized_end=180
# @@protoc_insertion_point(module_scope)
