# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/Time.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros import builtins_pb2 as ros_dot_builtins__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ros/std_msgs/Time.proto\x12\x0cros.std_msgs\x1a\x12ros/builtins.proto\"\x1f\n\x04Time\x12\x17\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\t.ros.Timeb\x06proto3')



_TIME = DESCRIPTOR.message_types_by_name['Time']
Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'ros.std_msgs.Time_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.Time)
  })
_sym_db.RegisterMessage(Time)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIME._serialized_start=61
  _TIME._serialized_end=92
# @@protoc_insertion_point(module_scope)
