# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/UInt64.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ros/std_msgs/UInt64.proto\x12\x0cros.std_msgs\"\x16\n\x06UInt64\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x04\x62\x06proto3')



_UINT64 = DESCRIPTOR.message_types_by_name['UInt64']
UInt64 = _reflection.GeneratedProtocolMessageType('UInt64', (_message.Message,), {
  'DESCRIPTOR' : _UINT64,
  '__module__' : 'ros.std_msgs.UInt64_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.UInt64)
  })
_sym_db.RegisterMessage(UInt64)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UINT64._serialized_start=43
  _UINT64._serialized_end=65
# @@protoc_insertion_point(module_scope)
