# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/std_msgs/UInt64MultiArray.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.std_msgs import MultiArrayLayout_pb2 as ros_dot_std__msgs_dot_MultiArrayLayout__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ros/std_msgs/UInt64MultiArray.proto\x12\x0cros.std_msgs\x1a#ros/std_msgs/MultiArrayLayout.proto\"P\n\x10UInt64MultiArray\x12.\n\x06layout\x18\x01 \x01(\x0b\x32\x1e.ros.std_msgs.MultiArrayLayout\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x04\x62\x06proto3')



_UINT64MULTIARRAY = DESCRIPTOR.message_types_by_name['UInt64MultiArray']
UInt64MultiArray = _reflection.GeneratedProtocolMessageType('UInt64MultiArray', (_message.Message,), {
  'DESCRIPTOR' : _UINT64MULTIARRAY,
  '__module__' : 'ros.std_msgs.UInt64MultiArray_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.UInt64MultiArray)
  })
_sym_db.RegisterMessage(UInt64MultiArray)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UINT64MULTIARRAY._serialized_start=90
  _UINT64MULTIARRAY._serialized_end=170
# @@protoc_insertion_point(module_scope)
