# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/shape_msgs/SolidPrimitive.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ros/shape_msgs/SolidPrimitive.proto\x12\x0eros.shape_msgs\"2\n\x0eSolidPrimitive\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x12\n\ndimensions\x18\x02 \x03(\x01\x62\x06proto3')



_SOLIDPRIMITIVE = DESCRIPTOR.message_types_by_name['SolidPrimitive']
SolidPrimitive = _reflection.GeneratedProtocolMessageType('SolidPrimitive', (_message.Message,), {
  'DESCRIPTOR' : _SOLIDPRIMITIVE,
  '__module__' : 'ros.shape_msgs.SolidPrimitive_pb2'
  # @@protoc_insertion_point(class_scope:ros.shape_msgs.SolidPrimitive)
  })
_sym_db.RegisterMessage(SolidPrimitive)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOLIDPRIMITIVE._serialized_start=55
  _SOLIDPRIMITIVE._serialized_end=105
# @@protoc_insertion_point(module_scope)
