# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/Inertia.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Vector3_pb2 as ros_dot_geometry__msgs_dot_Vector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fros/geometry_msgs/Inertia.proto\x12\x11ros.geometry_msgs\x1a\x1fros/geometry_msgs/Vector3.proto\"\x8b\x01\n\x07Inertia\x12\t\n\x01m\x18\x01 \x01(\x01\x12\'\n\x03\x63om\x18\x02 \x01(\x0b\x32\x1a.ros.geometry_msgs.Vector3\x12\x0b\n\x03ixx\x18\x03 \x01(\x01\x12\x0b\n\x03ixy\x18\x04 \x01(\x01\x12\x0b\n\x03ixz\x18\x05 \x01(\x01\x12\x0b\n\x03iyy\x18\x06 \x01(\x01\x12\x0b\n\x03iyz\x18\x07 \x01(\x01\x12\x0b\n\x03izz\x18\x08 \x01(\x01\x62\x06proto3')



_INERTIA = DESCRIPTOR.message_types_by_name['Inertia']
Inertia = _reflection.GeneratedProtocolMessageType('Inertia', (_message.Message,), {
  'DESCRIPTOR' : _INERTIA,
  '__module__' : 'ros.geometry_msgs.Inertia_pb2'
  # @@protoc_insertion_point(class_scope:ros.geometry_msgs.Inertia)
  })
_sym_db.RegisterMessage(Inertia)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INERTIA._serialized_start=88
  _INERTIA._serialized_end=227
# @@protoc_insertion_point(module_scope)
