# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/PolygonStamped.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Polygon_pb2 as ros_dot_geometry__msgs_dot_Polygon__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ros/geometry_msgs/PolygonStamped.proto\x12\x11ros.geometry_msgs\x1a\x1fros/geometry_msgs/Polygon.proto\x1a\x19ros/std_msgs/Header.proto\"c\n\x0ePolygonStamped\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12+\n\x07polygon\x18\x02 \x01(\x0b\x32\x1a.ros.geometry_msgs.Polygonb\x06proto3')



_POLYGONSTAMPED = DESCRIPTOR.message_types_by_name['PolygonStamped']
PolygonStamped = _reflection.GeneratedProtocolMessageType('PolygonStamped', (_message.Message,), {
  'DESCRIPTOR' : _POLYGONSTAMPED,
  '__module__' : 'ros.geometry_msgs.PolygonStamped_pb2'
  # @@protoc_insertion_point(class_scope:ros.geometry_msgs.PolygonStamped)
  })
_sym_db.RegisterMessage(PolygonStamped)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POLYGONSTAMPED._serialized_start=121
  _POLYGONSTAMPED._serialized_end=220
# @@protoc_insertion_point(module_scope)
