# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/Pose.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Point_pb2 as ros_dot_geometry__msgs_dot_Point__pb2
from ros.geometry_msgs import Quaternion_pb2 as ros_dot_geometry__msgs_dot_Quaternion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cros/geometry_msgs/Pose.proto\x12\x11ros.geometry_msgs\x1a\x1dros/geometry_msgs/Point.proto\x1a\"ros/geometry_msgs/Quaternion.proto\"f\n\x04Pose\x12*\n\x08position\x18\x01 \x01(\x0b\x32\x18.ros.geometry_msgs.Point\x12\x32\n\x0borientation\x18\x02 \x01(\x0b\x32\x1d.ros.geometry_msgs.Quaternionb\x06proto3')



_POSE = DESCRIPTOR.message_types_by_name['Pose']
Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {
  'DESCRIPTOR' : _POSE,
  '__module__' : 'ros.geometry_msgs.Pose_pb2'
  # @@protoc_insertion_point(class_scope:ros.geometry_msgs.Pose)
  })
_sym_db.RegisterMessage(Pose)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSE._serialized_start=118
  _POSE._serialized_end=220
# @@protoc_insertion_point(module_scope)
