# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/TransformStamped.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Transform_pb2 as ros_dot_geometry__msgs_dot_Transform__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(ros/geometry_msgs/TransformStamped.proto\x12\x11ros.geometry_msgs\x1a!ros/geometry_msgs/Transform.proto\x1a\x19ros/std_msgs/Header.proto\"\x81\x01\n\x10TransformStamped\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x16\n\x0e\x63hild_frame_id\x18\x02 \x01(\t\x12/\n\ttransform\x18\x03 \x01(\x0b\x32\x1c.ros.geometry_msgs.Transformb\x06proto3')



_TRANSFORMSTAMPED = DESCRIPTOR.message_types_by_name['TransformStamped']
TransformStamped = _reflection.GeneratedProtocolMessageType('TransformStamped', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORMSTAMPED,
  '__module__' : 'ros.geometry_msgs.TransformStamped_pb2'
  # @@protoc_insertion_point(class_scope:ros.geometry_msgs.TransformStamped)
  })
_sym_db.RegisterMessage(TransformStamped)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSFORMSTAMPED._serialized_start=126
  _TRANSFORMSTAMPED._serialized_end=255
# @@protoc_insertion_point(module_scope)
