# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/Wrench.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Vector3_pb2 as ros_dot_geometry__msgs_dot_Vector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eros/geometry_msgs/Wrench.proto\x12\x11ros.geometry_msgs\x1a\x1fros/geometry_msgs/Vector3.proto\"_\n\x06Wrench\x12)\n\x05\x66orce\x18\x01 \x01(\x0b\x32\x1a.ros.geometry_msgs.Vector3\x12*\n\x06torque\x18\x02 \x01(\x0b\x32\x1a.ros.geometry_msgs.Vector3b\x06proto3')



_WRENCH = DESCRIPTOR.message_types_by_name['Wrench']
Wrench = _reflection.GeneratedProtocolMessageType('Wrench', (_message.Message,), {
  'DESCRIPTOR' : _WRENCH,
  '__module__' : 'ros.geometry_msgs.Wrench_pb2'
  # @@protoc_insertion_point(class_scope:ros.geometry_msgs.Wrench)
  })
_sym_db.RegisterMessage(Wrench)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WRENCH._serialized_start=86
  _WRENCH._serialized_end=181
# @@protoc_insertion_point(module_scope)
