# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/WrenchStamped.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Wrench_pb2 as ros_dot_geometry__msgs_dot_Wrench__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%ros/geometry_msgs/WrenchStamped.proto\x12\x11ros.geometry_msgs\x1a\x1eros/geometry_msgs/Wrench.proto\x1a\x19ros/std_msgs/Header.proto\"`\n\rWrenchStamped\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12)\n\x06wrench\x18\x02 \x01(\x0b\x32\x19.ros.geometry_msgs.Wrenchb\x06proto3')



_WRENCHSTAMPED = DESCRIPTOR.message_types_by_name['WrenchStamped']
WrenchStamped = _reflection.GeneratedProtocolMessageType('WrenchStamped', (_message.Message,), {
  'DESCRIPTOR' : _WRENCHSTAMPED,
  '__module__' : 'ros.geometry_msgs.WrenchStamped_pb2'
  # @@protoc_insertion_point(class_scope:ros.geometry_msgs.WrenchStamped)
  })
_sym_db.RegisterMessage(WrenchStamped)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WRENCHSTAMPED._serialized_start=119
  _WRENCHSTAMPED._serialized_end=215
# @@protoc_insertion_point(module_scope)
