# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/rcl_interfaces/Log.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros import builtins_pb2 as ros_dot_builtins__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cros/rcl_interfaces/Log.proto\x12\x12ros.rcl_interfaces\x1a\x12ros/builtins.proto\"w\n\x03Log\x12\x18\n\x05stamp\x18\x01 \x01(\x0b\x32\t.ros.Time\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0b\n\x03msg\x18\x04 \x01(\t\x12\x0c\n\x04\x66ile\x18\x05 \x01(\t\x12\x10\n\x08\x66unction\x18\x06 \x01(\t\x12\x0c\n\x04line\x18\x07 \x01(\rb\x06proto3')



_LOG = DESCRIPTOR.message_types_by_name['Log']
Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), {
  'DESCRIPTOR' : _LOG,
  '__module__' : 'ros.rcl_interfaces.Log_pb2'
  # @@protoc_insertion_point(class_scope:ros.rcl_interfaces.Log)
  })
_sym_db.RegisterMessage(Log)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOG._serialized_start=72
  _LOG._serialized_end=191
# @@protoc_insertion_point(module_scope)
