# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/diagnostic_msgs/KeyValue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"ros/diagnostic_msgs/KeyValue.proto\x12\x13ros.diagnostic_msgs\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3')



_KEYVALUE = DESCRIPTOR.message_types_by_name['KeyValue']
KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUE,
  '__module__' : 'ros.diagnostic_msgs.KeyValue_pb2'
  # @@protoc_insertion_point(class_scope:ros.diagnostic_msgs.KeyValue)
  })
_sym_db.RegisterMessage(KeyValue)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEYVALUE._serialized_start=59
  _KEYVALUE._serialized_end=97
# @@protoc_insertion_point(module_scope)
