# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/rosgraph_msgs/Clock.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros import builtins_pb2 as ros_dot_builtins__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dros/rosgraph_msgs/Clock.proto\x12\x11ros.rosgraph_msgs\x1a\x12ros/builtins.proto\"!\n\x05\x43lock\x12\x18\n\x05\x63lock\x18\x01 \x01(\x0b\x32\t.ros.Timeb\x06proto3')



_CLOCK = DESCRIPTOR.message_types_by_name['Clock']
Clock = _reflection.GeneratedProtocolMessageType('Clock', (_message.Message,), {
  'DESCRIPTOR' : _CLOCK,
  '__module__' : 'ros.rosgraph_msgs.Clock_pb2'
  # @@protoc_insertion_point(class_scope:ros.rosgraph_msgs.Clock)
  })
_sym_db.RegisterMessage(Clock)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLOCK._serialized_start=72
  _CLOCK._serialized_end=105
# @@protoc_insertion_point(module_scope)
