# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/JoyFeedback.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ros/sensor_msgs/JoyFeedback.proto\x12\x0fros.sensor_msgs\":\n\x0bJoyFeedback\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x11\n\tintensity\x18\x03 \x01(\x02\x62\x06proto3')



_JOYFEEDBACK = DESCRIPTOR.message_types_by_name['JoyFeedback']
JoyFeedback = _reflection.GeneratedProtocolMessageType('JoyFeedback', (_message.Message,), {
  'DESCRIPTOR' : _JOYFEEDBACK,
  '__module__' : 'ros.sensor_msgs.JoyFeedback_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.JoyFeedback)
  })
_sym_db.RegisterMessage(JoyFeedback)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOYFEEDBACK._serialized_start=54
  _JOYFEEDBACK._serialized_end=112
# @@protoc_insertion_point(module_scope)
