# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/LaserEcho.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fros/sensor_msgs/LaserEcho.proto\x12\x0fros.sensor_msgs\"\x1b\n\tLaserEcho\x12\x0e\n\x06\x65\x63hoes\x18\x01 \x03(\x02\x62\x06proto3')



_LASERECHO = DESCRIPTOR.message_types_by_name['LaserEcho']
LaserEcho = _reflection.GeneratedProtocolMessageType('LaserEcho', (_message.Message,), {
  'DESCRIPTOR' : _LASERECHO,
  '__module__' : 'ros.sensor_msgs.LaserEcho_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.LaserEcho)
  })
_sym_db.RegisterMessage(LaserEcho)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LASERECHO._serialized_start=52
  _LASERECHO._serialized_end=79
# @@protoc_insertion_point(module_scope)
