# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/LaserScan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fros/sensor_msgs/LaserScan.proto\x12\x0fros.sensor_msgs\x1a\x19ros/std_msgs/Header.proto\"\xe6\x01\n\tLaserScan\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x11\n\tangle_min\x18\x02 \x01(\x02\x12\x11\n\tangle_max\x18\x03 \x01(\x02\x12\x17\n\x0f\x61ngle_increment\x18\x04 \x01(\x02\x12\x16\n\x0etime_increment\x18\x05 \x01(\x02\x12\x11\n\tscan_time\x18\x06 \x01(\x02\x12\x11\n\trange_min\x18\x07 \x01(\x02\x12\x11\n\trange_max\x18\x08 \x01(\x02\x12\x0e\n\x06ranges\x18\t \x03(\x02\x12\x13\n\x0bintensities\x18\n \x03(\x02\x62\x06proto3')



_LASERSCAN = DESCRIPTOR.message_types_by_name['LaserScan']
LaserScan = _reflection.GeneratedProtocolMessageType('LaserScan', (_message.Message,), {
  'DESCRIPTOR' : _LASERSCAN,
  '__module__' : 'ros.sensor_msgs.LaserScan_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.LaserScan)
  })
_sym_db.RegisterMessage(LaserScan)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LASERSCAN._serialized_start=80
  _LASERSCAN._serialized_end=310
# @@protoc_insertion_point(module_scope)
