# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/MagneticField.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Vector3_pb2 as ros_dot_geometry__msgs_dot_Vector3__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ros/sensor_msgs/MagneticField.proto\x12\x0fros.sensor_msgs\x1a\x1fros/geometry_msgs/Vector3.proto\x1a\x19ros/std_msgs/Header.proto\"\x8c\x01\n\rMagneticField\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x32\n\x0emagnetic_field\x18\x02 \x01(\x0b\x32\x1a.ros.geometry_msgs.Vector3\x12!\n\x19magnetic_field_covariance\x18\x03 \x03(\x01\x62\x06proto3')



_MAGNETICFIELD = DESCRIPTOR.message_types_by_name['MagneticField']
MagneticField = _reflection.GeneratedProtocolMessageType('MagneticField', (_message.Message,), {
  'DESCRIPTOR' : _MAGNETICFIELD,
  '__module__' : 'ros.sensor_msgs.MagneticField_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.MagneticField)
  })
_sym_db.RegisterMessage(MagneticField)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAGNETICFIELD._serialized_start=117
  _MAGNETICFIELD._serialized_end=257
# @@protoc_insertion_point(module_scope)
