# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/NavSatStatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"ros/sensor_msgs/NavSatStatus.proto\x12\x0fros.sensor_msgs\"/\n\x0cNavSatStatus\x12\x0e\n\x06status\x18\x01 \x01(\x11\x12\x0f\n\x07service\x18\x02 \x01(\x05\x62\x06proto3')



_NAVSATSTATUS = DESCRIPTOR.message_types_by_name['NavSatStatus']
NavSatStatus = _reflection.GeneratedProtocolMessageType('NavSatStatus', (_message.Message,), {
  'DESCRIPTOR' : _NAVSATSTATUS,
  '__module__' : 'ros.sensor_msgs.NavSatStatus_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.NavSatStatus)
  })
_sym_db.RegisterMessage(NavSatStatus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVSATSTATUS._serialized_start=55
  _NAVSATSTATUS._serialized_end=102
# @@protoc_insertion_point(module_scope)
