# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/PointField.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ros/sensor_msgs/PointField.proto\x12\x0fros.sensor_msgs\"K\n\nPointField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\r\x12\x10\n\x08\x64\x61tatype\x18\x03 \x01(\x05\x12\r\n\x05\x63ount\x18\x04 \x01(\rb\x06proto3')



_POINTFIELD = DESCRIPTOR.message_types_by_name['PointField']
PointField = _reflection.GeneratedProtocolMessageType('PointField', (_message.Message,), {
  'DESCRIPTOR' : _POINTFIELD,
  '__module__' : 'ros.sensor_msgs.PointField_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.PointField)
  })
_sym_db.RegisterMessage(PointField)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINTFIELD._serialized_start=53
  _POINTFIELD._serialized_end=128
# @@protoc_insertion_point(module_scope)
