# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/RegionOfInterest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ros/sensor_msgs/RegionOfInterest.proto\x12\x0fros.sensor_msgs\"i\n\x10RegionOfInterest\x12\x10\n\x08x_offset\x18\x01 \x01(\r\x12\x10\n\x08y_offset\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\r\n\x05width\x18\x04 \x01(\r\x12\x12\n\ndo_rectify\x18\x05 \x01(\x08\x62\x06proto3')



_REGIONOFINTEREST = DESCRIPTOR.message_types_by_name['RegionOfInterest']
RegionOfInterest = _reflection.GeneratedProtocolMessageType('RegionOfInterest', (_message.Message,), {
  'DESCRIPTOR' : _REGIONOFINTEREST,
  '__module__' : 'ros.sensor_msgs.RegionOfInterest_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.RegionOfInterest)
  })
_sym_db.RegisterMessage(RegionOfInterest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGIONOFINTEREST._serialized_start=59
  _REGIONOFINTEREST._serialized_end=164
# @@protoc_insertion_point(module_scope)
