# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/RelativeHumidity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ros/sensor_msgs/RelativeHumidity.proto\x12\x0fros.sensor_msgs\x1a\x19ros/std_msgs/Header.proto\"e\n\x10RelativeHumidity\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x19\n\x11relative_humidity\x18\x02 \x01(\x01\x12\x10\n\x08variance\x18\x03 \x01(\x01\x62\x06proto3')



_RELATIVEHUMIDITY = DESCRIPTOR.message_types_by_name['RelativeHumidity']
RelativeHumidity = _reflection.GeneratedProtocolMessageType('RelativeHumidity', (_message.Message,), {
  'DESCRIPTOR' : _RELATIVEHUMIDITY,
  '__module__' : 'ros.sensor_msgs.RelativeHumidity_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.RelativeHumidity)
  })
_sym_db.RegisterMessage(RelativeHumidity)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RELATIVEHUMIDITY._serialized_start=86
  _RELATIVEHUMIDITY._serialized_end=187
# @@protoc_insertion_point(module_scope)
