# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/visualization_msgs/ImageMarker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros import builtins_pb2 as ros_dot_builtins__pb2
from ros.geometry_msgs import Point_pb2 as ros_dot_geometry__msgs_dot_Point__pb2
from ros.std_msgs import ColorRGBA_pb2 as ros_dot_std__msgs_dot_ColorRGBA__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(ros/visualization_msgs/ImageMarker.proto\x12\x16ros.visualization_msgs\x1a\x12ros/builtins.proto\x1a\x1dros/geometry_msgs/Point.proto\x1a\x1cros/std_msgs/ColorRGBA.proto\x1a\x19ros/std_msgs/Header.proto\"\x8d\x03\n\x0bImageMarker\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\n\n\x02ns\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\x05\x12*\n\x08position\x18\x06 \x01(\x0b\x32\x18.ros.geometry_msgs.Point\x12\r\n\x05scale\x18\x07 \x01(\x02\x12.\n\routline_color\x18\x08 \x01(\x0b\x32\x17.ros.std_msgs.ColorRGBA\x12\x0e\n\x06\x66illed\x18\t \x01(\x05\x12+\n\nfill_color\x18\n \x01(\x0b\x32\x17.ros.std_msgs.ColorRGBA\x12\x1f\n\x08lifetime\x18\x0b \x01(\x0b\x32\r.ros.Duration\x12(\n\x06points\x18\x0c \x03(\x0b\x32\x18.ros.geometry_msgs.Point\x12/\n\x0eoutline_colors\x18\r \x03(\x0b\x32\x17.ros.std_msgs.ColorRGBAb\x06proto3')



_IMAGEMARKER = DESCRIPTOR.message_types_by_name['ImageMarker']
ImageMarker = _reflection.GeneratedProtocolMessageType('ImageMarker', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEMARKER,
  '__module__' : 'ros.visualization_msgs.ImageMarker_pb2'
  # @@protoc_insertion_point(class_scope:ros.visualization_msgs.ImageMarker)
  })
_sym_db.RegisterMessage(ImageMarker)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEMARKER._serialized_start=177
  _IMAGEMARKER._serialized_end=574
# @@protoc_insertion_point(module_scope)
