# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/nav_msgs/MapMetaData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros import builtins_pb2 as ros_dot_builtins__pb2
from ros.geometry_msgs import Pose_pb2 as ros_dot_geometry__msgs_dot_Pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eros/nav_msgs/MapMetaData.proto\x12\x0cros.nav_msgs\x1a\x12ros/builtins.proto\x1a\x1cros/geometry_msgs/Pose.proto\"\x8b\x01\n\x0bMapMetaData\x12 \n\rmap_load_time\x18\x01 \x01(\x0b\x32\t.ros.Time\x12\x12\n\nresolution\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\'\n\x06origin\x18\x05 \x01(\x0b\x32\x17.ros.geometry_msgs.Poseb\x06proto3')



_MAPMETADATA = DESCRIPTOR.message_types_by_name['MapMetaData']
MapMetaData = _reflection.GeneratedProtocolMessageType('MapMetaData', (_message.Message,), {
  'DESCRIPTOR' : _MAPMETADATA,
  '__module__' : 'ros.nav_msgs.MapMetaData_pb2'
  # @@protoc_insertion_point(class_scope:ros.nav_msgs.MapMetaData)
  })
_sym_db.RegisterMessage(MapMetaData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPMETADATA._serialized_start=99
  _MAPMETADATA._serialized_end=238
# @@protoc_insertion_point(module_scope)
