# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/diagnostic_msgs/DiagnosticStatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.diagnostic_msgs import KeyValue_pb2 as ros_dot_diagnostic__msgs_dot_KeyValue__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*ros/diagnostic_msgs/DiagnosticStatus.proto\x12\x13ros.diagnostic_msgs\x1a\"ros/diagnostic_msgs/KeyValue.proto\"\x84\x01\n\x10\x44iagnosticStatus\x12\r\n\x05level\x18\x01 \x01(\x11\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x13\n\x0bhardware_id\x18\x04 \x01(\t\x12-\n\x06values\x18\x05 \x03(\x0b\x32\x1d.ros.diagnostic_msgs.KeyValueb\x06proto3')



_DIAGNOSTICSTATUS = DESCRIPTOR.message_types_by_name['DiagnosticStatus']
DiagnosticStatus = _reflection.GeneratedProtocolMessageType('DiagnosticStatus', (_message.Message,), {
  'DESCRIPTOR' : _DIAGNOSTICSTATUS,
  '__module__' : 'ros.diagnostic_msgs.DiagnosticStatus_pb2'
  # @@protoc_insertion_point(class_scope:ros.diagnostic_msgs.DiagnosticStatus)
  })
_sym_db.RegisterMessage(DiagnosticStatus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIAGNOSTICSTATUS._serialized_start=104
  _DIAGNOSTICSTATUS._serialized_end=236
# @@protoc_insertion_point(module_scope)
