# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/nav_msgs/OccupancyGrid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.nav_msgs import MapMetaData_pb2 as ros_dot_nav__msgs_dot_MapMetaData__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ros/nav_msgs/OccupancyGrid.proto\x12\x0cros.nav_msgs\x1a\x1eros/nav_msgs/MapMetaData.proto\x1a\x19ros/std_msgs/Header.proto\"l\n\rOccupancyGrid\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\'\n\x04info\x18\x02 \x01(\x0b\x32\x19.ros.nav_msgs.MapMetaData\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x11\x62\x06proto3')



_OCCUPANCYGRID = DESCRIPTOR.message_types_by_name['OccupancyGrid']
OccupancyGrid = _reflection.GeneratedProtocolMessageType('OccupancyGrid', (_message.Message,), {
  'DESCRIPTOR' : _OCCUPANCYGRID,
  '__module__' : 'ros.nav_msgs.OccupancyGrid_pb2'
  # @@protoc_insertion_point(class_scope:ros.nav_msgs.OccupancyGrid)
  })
_sym_db.RegisterMessage(OccupancyGrid)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OCCUPANCYGRID._serialized_start=109
  _OCCUPANCYGRID._serialized_end=217
# @@protoc_insertion_point(module_scope)
