# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/actionlib_msgs/GoalID.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros import builtins_pb2 as ros_dot_builtins__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fros/actionlib_msgs/GoalID.proto\x12\x12ros.actionlib_msgs\x1a\x12ros/builtins.proto\".\n\x06GoalID\x12\x18\n\x05stamp\x18\x01 \x01(\x0b\x32\t.ros.Time\x12\n\n\x02id\x18\x02 \x01(\tb\x06proto3')



_GOALID = DESCRIPTOR.message_types_by_name['GoalID']
GoalID = _reflection.GeneratedProtocolMessageType('GoalID', (_message.Message,), {
  'DESCRIPTOR' : _GOALID,
  '__module__' : 'ros.actionlib_msgs.GoalID_pb2'
  # @@protoc_insertion_point(class_scope:ros.actionlib_msgs.GoalID)
  })
_sym_db.RegisterMessage(GoalID)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GOALID._serialized_start=75
  _GOALID._serialized_end=121
# @@protoc_insertion_point(module_scope)
