# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/builtins.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ros/builtins.proto\x12\x03ros\"!\n\x04Time\x12\x0b\n\x03sec\x18\x01 \x01(\x07\x12\x0c\n\x04nsec\x18\x02 \x01(\x07\"%\n\x08\x44uration\x12\x0b\n\x03sec\x18\x01 \x01(\x07\x12\x0c\n\x04nsec\x18\x02 \x01(\x07\x62\x06proto3')



_TIME = DESCRIPTOR.message_types_by_name['Time']
_DURATION = DESCRIPTOR.message_types_by_name['Duration']
Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'ros.builtins_pb2'
  # @@protoc_insertion_point(class_scope:ros.Time)
  })
_sym_db.RegisterMessage(Time)

Duration = _reflection.GeneratedProtocolMessageType('Duration', (_message.Message,), {
  'DESCRIPTOR' : _DURATION,
  '__module__' : 'ros.builtins_pb2'
  # @@protoc_insertion_point(class_scope:ros.Duration)
  })
_sym_db.RegisterMessage(Duration)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIME._serialized_start=27
  _TIME._serialized_end=60
  _DURATION._serialized_start=62
  _DURATION._serialized_end=99
# @@protoc_insertion_point(module_scope)
