# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/Imu.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Quaternion_pb2 as ros_dot_geometry__msgs_dot_Quaternion__pb2
from ros.geometry_msgs import Vector3_pb2 as ros_dot_geometry__msgs_dot_Vector3__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ros/sensor_msgs/Imu.proto\x12\x0fros.sensor_msgs\x1a\"ros/geometry_msgs/Quaternion.proto\x1a\x1fros/geometry_msgs/Vector3.proto\x1a\x19ros/std_msgs/Header.proto\"\xbb\x02\n\x03Imu\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x32\n\x0borientation\x18\x02 \x01(\x0b\x32\x1d.ros.geometry_msgs.Quaternion\x12\x1e\n\x16orientation_covariance\x18\x03 \x03(\x01\x12\x34\n\x10\x61ngular_velocity\x18\x04 \x01(\x0b\x32\x1a.ros.geometry_msgs.Vector3\x12#\n\x1b\x61ngular_velocity_covariance\x18\x05 \x03(\x01\x12\x37\n\x13linear_acceleration\x18\x06 \x01(\x0b\x32\x1a.ros.geometry_msgs.Vector3\x12&\n\x1elinear_acceleration_covariance\x18\x07 \x03(\x01\x62\x06proto3')



_IMU = DESCRIPTOR.message_types_by_name['Imu']
Imu = _reflection.GeneratedProtocolMessageType('Imu', (_message.Message,), {
  'DESCRIPTOR' : _IMU,
  '__module__' : 'ros.sensor_msgs.Imu_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.Imu)
  })
_sym_db.RegisterMessage(Imu)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMU._serialized_start=143
  _IMU._serialized_end=458
# @@protoc_insertion_point(module_scope)
