# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/Joy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ros/sensor_msgs/Joy.proto\x12\x0fros.sensor_msgs\x1a\x19ros/std_msgs/Header.proto\"J\n\x03Joy\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x0c\n\x04\x61xes\x18\x02 \x03(\x02\x12\x0f\n\x07\x62uttons\x18\x03 \x03(\x05\x62\x06proto3')



_JOY = DESCRIPTOR.message_types_by_name['Joy']
Joy = _reflection.GeneratedProtocolMessageType('Joy', (_message.Message,), {
  'DESCRIPTOR' : _JOY,
  '__module__' : 'ros.sensor_msgs.Joy_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.Joy)
  })
_sym_db.RegisterMessage(Joy)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOY._serialized_start=73
  _JOY._serialized_end=147
# @@protoc_insertion_point(module_scope)
