# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/MultiDOFJointState.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Transform_pb2 as ros_dot_geometry__msgs_dot_Transform__pb2
from ros.geometry_msgs import Twist_pb2 as ros_dot_geometry__msgs_dot_Twist__pb2
from ros.geometry_msgs import Wrench_pb2 as ros_dot_geometry__msgs_dot_Wrench__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(ros/sensor_msgs/MultiDOFJointState.proto\x12\x0fros.sensor_msgs\x1a!ros/geometry_msgs/Transform.proto\x1a\x1dros/geometry_msgs/Twist.proto\x1a\x1eros/geometry_msgs/Wrench.proto\x1a\x19ros/std_msgs/Header.proto\"\xd5\x01\n\x12MultiDOFJointState\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x13\n\x0bjoint_names\x18\x02 \x03(\t\x12\x30\n\ntransforms\x18\x03 \x03(\x0b\x32\x1c.ros.geometry_msgs.Transform\x12\'\n\x05twist\x18\x04 \x03(\x0b\x32\x18.ros.geometry_msgs.Twist\x12)\n\x06wrench\x18\x05 \x03(\x0b\x32\x19.ros.geometry_msgs.Wrenchb\x06proto3')



_MULTIDOFJOINTSTATE = DESCRIPTOR.message_types_by_name['MultiDOFJointState']
MultiDOFJointState = _reflection.GeneratedProtocolMessageType('MultiDOFJointState', (_message.Message,), {
  'DESCRIPTOR' : _MULTIDOFJOINTSTATE,
  '__module__' : 'ros.sensor_msgs.MultiDOFJointState_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.MultiDOFJointState)
  })
_sym_db.RegisterMessage(MultiDOFJointState)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MULTIDOFJOINTSTATE._serialized_start=187
  _MULTIDOFJOINTSTATE._serialized_end=400
# @@protoc_insertion_point(module_scope)
