# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/MultiEchoLaserScan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.sensor_msgs import LaserEcho_pb2 as ros_dot_sensor__msgs_dot_LaserEcho__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(ros/sensor_msgs/MultiEchoLaserScan.proto\x12\x0fros.sensor_msgs\x1a\x1fros/sensor_msgs/LaserEcho.proto\x1a\x19ros/std_msgs/Header.proto\"\xa7\x02\n\x12MultiEchoLaserScan\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x11\n\tangle_min\x18\x02 \x01(\x02\x12\x11\n\tangle_max\x18\x03 \x01(\x02\x12\x17\n\x0f\x61ngle_increment\x18\x04 \x01(\x02\x12\x16\n\x0etime_increment\x18\x05 \x01(\x02\x12\x11\n\tscan_time\x18\x06 \x01(\x02\x12\x11\n\trange_min\x18\x07 \x01(\x02\x12\x11\n\trange_max\x18\x08 \x01(\x02\x12*\n\x06ranges\x18\t \x03(\x0b\x32\x1a.ros.sensor_msgs.LaserEcho\x12/\n\x0bintensities\x18\n \x03(\x0b\x32\x1a.ros.sensor_msgs.LaserEchob\x06proto3')



_MULTIECHOLASERSCAN = DESCRIPTOR.message_types_by_name['MultiEchoLaserScan']
MultiEchoLaserScan = _reflection.GeneratedProtocolMessageType('MultiEchoLaserScan', (_message.Message,), {
  'DESCRIPTOR' : _MULTIECHOLASERSCAN,
  '__module__' : 'ros.sensor_msgs.MultiEchoLaserScan_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.MultiEchoLaserScan)
  })
_sym_db.RegisterMessage(MultiEchoLaserScan)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MULTIECHOLASERSCAN._serialized_start=122
  _MULTIECHOLASERSCAN._serialized_end=417
# @@protoc_insertion_point(module_scope)
