# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/TimeReference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros import builtins_pb2 as ros_dot_builtins__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ros/sensor_msgs/TimeReference.proto\x12\x0fros.sensor_msgs\x1a\x12ros/builtins.proto\x1a\x19ros/std_msgs/Header.proto\"b\n\rTimeReference\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x1b\n\x08time_ref\x18\x02 \x01(\x0b\x32\t.ros.Time\x12\x0e\n\x06source\x18\x03 \x01(\tb\x06proto3')



_TIMEREFERENCE = DESCRIPTOR.message_types_by_name['TimeReference']
TimeReference = _reflection.GeneratedProtocolMessageType('TimeReference', (_message.Message,), {
  'DESCRIPTOR' : _TIMEREFERENCE,
  '__module__' : 'ros.sensor_msgs.TimeReference_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.TimeReference)
  })
_sym_db.RegisterMessage(TimeReference)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEREFERENCE._serialized_start=103
  _TIMEREFERENCE._serialized_end=201
# @@protoc_insertion_point(module_scope)
