# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/stereo_msgs/DisparityImage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.sensor_msgs import Image_pb2 as ros_dot_sensor__msgs_dot_Image__pb2
from ros.sensor_msgs import RegionOfInterest_pb2 as ros_dot_sensor__msgs_dot_RegionOfInterest__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ros/stereo_msgs/DisparityImage.proto\x12\x0fros.stereo_msgs\x1a\x1bros/sensor_msgs/Image.proto\x1a&ros/sensor_msgs/RegionOfInterest.proto\x1a\x19ros/std_msgs/Header.proto\"\xeb\x01\n\x0e\x44isparityImage\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12%\n\x05image\x18\x02 \x01(\x0b\x32\x16.ros.sensor_msgs.Image\x12\t\n\x01\x66\x18\x03 \x01(\x02\x12\t\n\x01T\x18\x04 \x01(\x02\x12\x37\n\x0cvalid_window\x18\x05 \x01(\x0b\x32!.ros.sensor_msgs.RegionOfInterest\x12\x15\n\rmin_disparity\x18\x06 \x01(\x02\x12\x15\n\rmax_disparity\x18\x07 \x01(\x02\x12\x0f\n\x07\x64\x65lta_d\x18\x08 \x01(\x02\x62\x06proto3')



_DISPARITYIMAGE = DESCRIPTOR.message_types_by_name['DisparityImage']
DisparityImage = _reflection.GeneratedProtocolMessageType('DisparityImage', (_message.Message,), {
  'DESCRIPTOR' : _DISPARITYIMAGE,
  '__module__' : 'ros.stereo_msgs.DisparityImage_pb2'
  # @@protoc_insertion_point(class_scope:ros.stereo_msgs.DisparityImage)
  })
_sym_db.RegisterMessage(DisparityImage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISPARITYIMAGE._serialized_start=154
  _DISPARITYIMAGE._serialized_end=389
# @@protoc_insertion_point(module_scope)
